name: OVOS Make Arch Packages
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    container:
      image: manjarolinux/base:latest
      options: --user builder
    steps:
      - name: Install Dependencies
        run: |
          sudo pacman -Syyu --noconfirm
          sudo pacman -S --noconfirm base-devel git
      - name: Clone Repositories
        run: |
          git clone https://github.com/OpenVoiceOS/ovos-arch-repo.git /builder/ovos-arch-repo
          git clone https://github.com/OpenVoiceOS/ovos-binary-shop.git /builder/ovos-binary-shop
      - name: Build Packages X86_64
        run: |
          for package in python-memory-tempfile python-combo-lock python-json-database python-kthread python-ovos-utils python-mycroft-messagebus-client python-ovos-backend-client python-rich-click python-ovos-config python-quebra-frases python-ovos-lingua-franca python-langcodes python-ovos-bus-client python-ovos-plugin-manager python-ovos-workshop python-simplematch python-padacioso python-ovos-core python-ovos-gui; do
            echo $package
            cd /builder/ovos-binary-shop/$package
            makepkg -si --noconfirm
            mkdir -p /builder/ovos-arch-repo/x86_64/
            mv *.pkg.tar.zst /builder/ovos-arch-repo/x86_64/
          done
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          cwd: "./builder/ovos-arch-repo"
          message: "Update Packages"
          add: "*"
