name: OVOS Make Arch Packages
on:
  push:
  workflow_dispatch:
    inputs:
      package_list:
        description: "Packages to Build"
        required: true

jobs:
  build:
    runs-on: self-hosted
    container:
      image: manjarolinux/base:latest
      options: --user builder
    steps:
      - name: Install Dependencies
        run: |
          sudo pacman -Syyu --noconfirm
          sudo pacman -S --noconfirm base-devel git
      - name: Clone Repositories
        run: |
          git clone https://github.com/OpenVoiceOS/ovos-arch-repo.git /builder/ovos-arch-repo
          git clone https://github.com/OpenVoiceOS/ovos-binary-shop.git /builder/ovos-binary-shop
      - name: Build Packages
        run: |
          cd /builder/ovos-binary-shop
          for package in "${{ inputs.package_list }}"; do
            cd $package
            makepkg -s --noconfirm
            mkdir -p /builder/ovos-arch-repo/x86_64/
            mv *.pkg.tar.zst /builder/ovos-arch-repo/x86_64/
          done
      - name: Repo Add Packages
        run: |
          cd /builder/ovos-arch-repo
          repo-add ovos-arch-repo.db.tar.gz *.pkg.tar.zst
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          cwd: "./builder/ovos-arch-repo"
          message: "Update Packages"
          add: "*"
