name: OVOS Make Arch Packages
on:
  push:
  workflow_dispatch:
    inputs:
      package_list:
        description: "Packages to Build"
        required: true

jobs:
  build:
    runs-on: self-hosted
    container:
      image: manjarolinux/base:latest
    steps:
      - name: Install Dependencies
        run: |
          sudo pacman -Syyu --noconfirm
          sudo pacman -S --noconfirm base-devel git
      - name: Clone Repositories
        run: |
          mkdir -p builder
          (cd builder && git clone https://github.com/OpenVoiceOS/ovos-arch-repo)
          (cd builder && git clone https://github.com/OpenVoiceOS/ovos-binary-shop)
      - name: Build Packages
        run: |
          cd builder/ovos-binary-shop
          for package in "${{ inputs.package_list }}"; do
            cd $package
            makepkg -s --noconfirm
            cp *.pkg.tar.zst ../ovos-arch-repo
            cd ..
          done
      - name: Repo Add Packages
        run: |
          cd builder/ovos-arch-repo
          repo-add ovos-arch-repo.db *.pkg.tar.zst
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          cwd: "./home/github_actions/builder/ovos-arch-repo"
          message: "Update Packages"
          add: "*"
