name: OVOS Make Arch Packages
on:
  push:
  workflow_dispatch:
    inputs:
      package_list:
        description: "Packages to Build"
        required: true

jobs:
  build:
    runs-on: self-hosted
    container:
      image: manjarolinux/base:latest
    steps:
      - name: Install Dependencies
        run: |
          sudo pacman -Syyu --noconfirm
          sudo pacman -S --noconfirm base-devel git
      - name: Checkout ovos-arch-repo
        uses: actions/checkout@v3
        with:
          repository: OpenVoiceOS/ovos-arch-repo
          ref: main
          path: builder/ovos-arch-repo
      - name: Checkout ovos-binary-shop
        uses: actions/checkout@v3
        with:
          repository: OpenVoiceOS/ovos-binary-shop
          ref: dev
          path: builder/ovos-binary-shop
      - name: Build Packages
        run: |
          cd builder/ovos-binary-shop
          for package in "${{ inputs.package_list }}"; do
            cd $package
            makepkg -s --noconfirm
            cp *.pkg.tar.zst ../ovos-arch-repo
            cd ..
          done
      - name: Repo Add Packages
        run: |
          cd builder/ovos-arch-repo
          repo-add ovos-arch-repo.db *.pkg.tar.zst
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          cwd: "./home/github_actions/builder/ovos-arch-repo"
          message: "Update Packages"
          add: "*"
