name: OVOS Make Arch Packages
on:
  push:
  workflow_dispatch:
    inputs:
      package_list:
        description: "Packages to Build"
        required: true

jobs:
  build:
    runs-on: self-hosted
    container:
      image: manjarolinux/base:latest
    steps:
      - name: Install Dependencies
        run: |
          sudo pacman -Syyu --noconfirm
          sudo pacman -S --noconfirm base-devel git
      - name: Create User
        run: |
          sudo useradd -m packagebuilder
          sudo usermod -aG wheel packagebuilder
          echo 'packagebuilder ALL=(ALL) NOPASSWD: ALL' | sudo tee -a /etc/sudoers
      - name: Clone Repositories
        run: |
          sudo -u packagebuilder git clone https://github.com/OpenVoiceOS/ovos-arch-repo.git /home/packagebuilder/ovos-arch-repo
          sudo -u packagebuilder git clone https://github.com/OpenVoiceOS/ovos-binary-shop.git /home/packagebuilder/ovos-binary-shop
      - name: Fix Permissions
        run: |
          sudo chmod -R 777 /home/packagebuilder
          sudo chmod -R 777 /home/packagebuilder/ovos-arch-repo
          sudo chmod -R 777 /home/packagebuilder/ovos-binary-shop
          sudo chown -R packagebuilder /home/packagebuilder
      - name: Build Packages
        run: |
          cd /home/packagebuilder/ovos-binary-shop
          for package in "${{ inputs.package_list }}"; do
            cd $package
            sudo -u packagebuilder makepkg -s --noconfirm
            sudo -u packagebuilder mv *.pkg.tar.zst /home/packagebuilder/ovos-arch-repo/x86_64/
          done
      - name: Repo Add Packages
        run: |
          cd /home/packagebuilder/ovos-arch-repo
          repo-add ovos-arch-repo.db.tar.gz *.pkg.tar.zst
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          cwd: "./home/packagebuilder/ovos-arch-repo"
          message: "Update Packages"
          add: "*"
