name: OVOS Run Repo Add on Arch Packages
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    container:
      image: manjarolinux/base:latest
      options: --user builder
    steps:
      - name: Install Dependencies
        run: |
          sudo pacman -Syyu --noconfirm
          sudo pacman -S --noconfirm base-devel git
      - name: Chown user
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE
          sudo chmod -R 777 /__w/ovos-arch-repo/ovos-arch-repo/builder/ovos-arch-repo/
          sudo chown -R $USER:$USER /__w/ovos-arch-repo/ovos-arch-repo/builder/
      - name: Clone OVOS Arch Repository
        uses: actions/checkout@v3
        with:
          repository: OpenVoiceOS/ovos-arch-repo
          ref: main
          path: builder/ovos-arch-repo
      - name: Run Repo-Add
        run: |
         cd ./builder/ovos-arch-repo
         repo-add ovos-arch-repo.db.tar.gz x86_64/*.pkg.tar.zst
         rm ovos-arch-repo.db
         rm ovos-arch-repo.files
         mv ovos-arch-repo.db.tar.gz ovos-arch-repo.db
         mv ovos-arch-repo.files.tar.gz ovos-arch-repo.files
      - name: Fix Git Errors and Cleanup
        run: |
         git config --global --add safe.directory /__w/ovos-arch-repo/ovos-arch-repo/builder/ovos-arch-repo
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          cwd: "./builder/ovos-arch-repo"
          message: "Update Packages"
          add: "*.db, *.files"
          push: true
